[package]
name = "tui_crudo"
version = "0.1.0"
edition = "2021"
[lib]
name = "tui_crudo"
path = "src/lib.rs"

[[bin]]
name = "tui_crudo"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.92"
chrono = "0.4.45"
crossterm = "0.29.0"
image = "0.25.10"
ratatui = { version = "0.30.2", features = ["crossterm"] }
ratatui-image = { version = "11.0.8", default-features = false, features = ["image-defaults", "crossterm"] }
sysinfo = "0.39.6"
tokio = { version = "1.53.1", features = ["full"] }
