#!/usr/bin/env bash
# Install a development-only Crudo launcher backed by a remote model endpoint.
#
# Usage:
#   bash scripts/install-crudo-luna.sh
#
# The launcher is installed at ~/.local/bin/crudo-luna. It never stores the
# credential in this repository. This is NOT sovereign mode: prompts and any
# files supplied to Crudo are sent to the configured remote endpoint.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RUST_ROOT="$REPO_ROOT/rust"
INSTALL_DIR="${HOME}/.local/bin"
CONFIG_DIR="${HOME}/.config/nuvai/crudo-luna"
CONFIG_FILE="$CONFIG_DIR/config.env"
TARGET="$INSTALL_DIR/crudo-luna"

if [[ ! -f "$RUST_ROOT/Cargo.toml" ]]; then
  printf 'Error: Rust workspace not found: %s\n' "$RUST_ROOT" >&2
  exit 1
fi

mkdir -p "$INSTALL_DIR"
(umask 077; mkdir -p "$CONFIG_DIR")
chmod 700 "$CONFIG_DIR"

endpoint="${CRUDO_LUNA_ENDPOINT:-${LUNACODE_ENDPOINT:-http://20.230.232.136:8081}}"
endpoint="${endpoint%/}"

if [[ -t 0 ]]; then
  printf 'Crudo remote development configuration\n'
  printf '%s\n' '────────────────────────────────────────'
  printf 'Endpoint: %s\n' "$endpoint"
  printf 'WARNING: this endpoint is remote; do not send confidential data.\n'
  read -r -s -p 'Enter Luna API key: ' api_key
  printf '\n'
else
  api_key="${CRUDO_LUNA_API_KEY:-${LUNACODE_API_KEY:-}}"
fi

if [[ -z "$api_key" ]]; then
  printf 'Error: CRUDO_LUNA_API_KEY (or LUNACODE_API_KEY) cannot be empty.\n' >&2
  exit 1
fi

if [[ "$endpoint" == */health || "$endpoint" == */v1/messages ]]; then
  printf 'Error: endpoint must be the API root, not /health or /v1/messages.\n' >&2
  exit 1
fi

model="${CRUDO_LUNA_MODEL:-${LUNACODE_MODEL:-gpt-5.6-luna}}"

(umask 077; {
  printf '# Generated by scripts/install-crudo-luna.sh\n'
  printf 'CRUDO_LUNA_ENDPOINT=%q\n' "$endpoint"
  printf 'CRUDO_LUNA_API_KEY=%q\n' "$api_key"
  printf 'CRUDO_LUNA_MODEL=%q\n' "$model"
  printf 'CRUDO_REPO_ROOT=%q\n' "$REPO_ROOT"
} > "$CONFIG_FILE")
chmod 600 "$CONFIG_FILE"

cat > "$TARGET" <<'LAUNCHER'
#!/usr/bin/env bash
# Development-only Crudo launcher for the remote Luna endpoint.
set -euo pipefail

CONFIG_FILE="${HOME}/.config/nuvai/crudo-luna/config.env"
if [[ ! -f "$CONFIG_FILE" ]]; then
  printf 'Error: Crudo Luna is not configured. Run scripts/install-crudo-luna.sh.\n' >&2
  exit 1
fi
# shellcheck disable=SC1090
source "$CONFIG_FILE"

: "${CRUDO_LUNA_ENDPOINT:?CRUDO_LUNA_ENDPOINT is missing}"
: "${CRUDO_LUNA_API_KEY:?CRUDO_LUNA_API_KEY is missing}"
: "${CRUDO_LUNA_MODEL:?CRUDO_LUNA_MODEL is missing}"
: "${CRUDO_REPO_ROOT:?CRUDO_REPO_ROOT is missing}"

if [[ "${CRUDO_LUNA_ENDPOINT}" != http://127.0.0.1:* &&
      "${CRUDO_LUNA_ENDPOINT}" != http://localhost:* &&
      "${CRUDO_LUNA_ENDPOINT}" != https://127.0.0.1:* &&
      "${CRUDO_LUNA_ENDPOINT}" != https://localhost:* ]]; then
  printf 'WARNING: Crudo is using a remote Luna endpoint: %s\n' "$CRUDO_LUNA_ENDPOINT" >&2
  printf 'WARNING: use synthetic/public data only; this is not sovereign mode.\n' >&2
fi

# Luna exposes an Anthropic-compatible /v1/messages API. The explicit
# `anthropic/` namespace makes Crudo select its Anthropic transport even though
# the hosted model's name begins with `gpt-`.
export ANTHROPIC_BASE_URL="${CRUDO_LUNA_ENDPOINT%/}"
export ANTHROPIC_API_KEY="$CRUDO_LUNA_API_KEY"
export ANTHROPIC_AUTH_TOKEN="$CRUDO_LUNA_API_KEY"
export CRUDO_MODEL="anthropic/${CRUDO_LUNA_MODEL#anthropic/}"
export ANTHROPIC_MODEL="$CRUDO_MODEL"
export ANTHROPIC_DEFAULT_OPUS_MODEL="$CRUDO_MODEL"
export ANTHROPIC_DEFAULT_SONNET_MODEL="$CRUDO_MODEL"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="$CRUDO_MODEL"
export CLAUDE_CODE_SUBAGENT_MODEL="$CRUDO_MODEL"
# Avoid ambient OpenAI credentials changing provider selection for this launcher.
unset OPENAI_BASE_URL OPENAI_API_KEY OPENAI_MODEL

if [[ "${1:-}" == "--config-status" ]]; then
  printf 'mode=development-remote\nendpoint=%s\nmodel=%s\napi_key=loaded\n' \
    "$CRUDO_LUNA_ENDPOINT" "$CRUDO_LUNA_MODEL"
  exit 0
fi

cd "$CRUDO_REPO_ROOT"
exec cargo run --manifest-path rust/Cargo.toml -p crudo-cli -- "$@"
LAUNCHER
chmod 755 "$TARGET"

case ":${PATH}:" in
  *":$INSTALL_DIR:"*) ;;
  *)
    shell_rc="$HOME/.bashrc"
    [[ "${SHELL##*/}" == zsh ]] && shell_rc="$HOME/.zshrc"
    path_line='export PATH="$HOME/.local/bin:$PATH"'
    if [[ ! -f "$shell_rc" ]] || ! grep -Fqx "$path_line" "$shell_rc"; then
      printf '\n# crudo-luna command\n%s\n' "$path_line" >> "$shell_rc"
    fi
    printf 'Added ~/.local/bin to %s. Open a new shell or run: source %s\n' "$shell_rc" "$shell_rc"
    ;;
esac

printf 'Installed: %s\n' "$TARGET"
printf 'Config:    %s (mode 600)\n' "$CONFIG_FILE"
printf 'Model:     %s\n' "$model"
printf '\nRun:       crudo-luna --config-status\n'
printf 'Then:      crudo-luna --help\n'
printf '\nThis launcher uses a remote endpoint and is for synthetic/public test data only.\n'
